### ISSUE TITLE
Missing console.c file

### ISSUE THREAD

**Issue by zhouxs1023** [travisg/3x86#1]
I had compiled this project, but the compilation fails；
Hint missing console.c file as below:
![360-163311257810291](https://user-images.githubusercontent.com/905931/66287988-39317c80-e90a-11e9-9f4f-b2a0db100a13.png)

**Comment by travisg** [comment]
Oh oops, will get that committed soon. Must have forgotten it.

**Comment by travisg** [comment]
Okay, should be fixed now.
